### ISSUE TITLE
Update Streets Data

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-layers-api#178]
### Streets data updates
- [x] 1- Wait for EDM to upload updated versions of the files
- [x] 2- Add Bytes link for metadata once available
- [x] 3- Update SQL in data/sources to reflect revised column names in the three dcm_streetnamechanges files. The other necessary changes have already been made in a draft PR. The column updates should be the last SQL update. https://github.com/NYCPlanning/labs-layers-api/pull/184/files.
- [x] 4- Add these view records to scripts/aliased-views/view_lookup.csv:
  - dcm,dcm_v202005,none
  - dcm_streetnamechanges_points,dcm_streetnamechanges_points_v202005,none
  - dcm_streetnamechanges_lines,dcm_streetnamechanges_lines_v202005,none
  - dcm_streetnamechanges_areas,dcm_streetnamechanges_areas_v202005,none
  - dcm_streetcenterline,dcm_streetcenterline_v202005,none
  - dcm_citymapalterations,dcm_citymapalterations_v202005,none
  - dcm_arterialsmajorstreets,dcm_arterialsmajorstreets_v202005,none
- [x] 5- Rail in the `dcm` table no longer has name labels. Delete name tooltip in layer styling.
- [x] 6- Add a new layer style for "Record Streets". These are a subset of "Unmapped Streets". They should be represented as a dotted black line the same width as "Mapped Street". We think "Record Street" should be indented under "Unmapped Street". Screenshot below of existing layers for reference. **[?] Does this require any front-end work?**
- [x] 7- After updates have been tested on staging, update the source file to use aliases and run the python script for view creation

![image](https://user-images.githubusercontent.com/13967925/73494959-93f05780-4383-11ea-9013-82ae7e80c4e1.png)

**Comment by andycochran** [comment]
> 6. Add a new layer style for "Record Streets". These are a subset of "Unmapped Streets". They should be represented as a dotted black line the same width as "Mapped Street". We think "Record Street" should be indented under "Unmapped Street". Screenshot below of existing layers for reference. [?] Does this require any front-end work?

## Indentation 

I assume the desire to indent Record Streets under Unmapped Streets is to indicate that they're a subset. But I don't think this visual cue alone is enough to clarify that fact. Indentation isn't used anywhere else, so it may lead to more confusion that if Record Streets just appeared below Unmapped Streets without indentation. 

This would also require rather involved changes to our legend syntax, Ember component, and CSS. I'd advise against this. We can revisit this as a new feature if the lack of indentation is leading to confusion. But I think there are more important ways we need to indicate the subset relationship. 

## Tooltip

More important than indentation is the language used for the tooltip to explain what a Record Street is. The Unmapped Street tooltip includes the phrase, "Record streets and private roads are examples of unmapped streets." The tooltip for Record Streets should include, "…is an unmapped street…" so that there's a two-way reference. 

_(Aside: we should look into making sure capitalization is used consistently in the legend names and tooltips.)_ 

## Symbology

What concerns me more than indentation or tooltip language — and this might conflict with existing standards — is how we plan to style the Record Streets. 

- If Record Streets are the same color and line thickness as Mapped Streets, it makes Record Streets seem more related to Mapped Streets than Unmapped Streets. 
- Record Streets being dotted is an attempt to indicate that they are a subset of Unmapped Streets. However, by creating a symbology for a subset of Unmapped Streets, the symbology for Unmapped Street becomes inaccurate. It means that "gray, dotted, thin" no longer means "Unmapped Street." The only style that represents Unmapped Street is  "dotted."

What is the reasoning for Record Streets be symbolized thicker and darker than Unmapped Streets? 

### Brainstorming a solution: 
It may make more sense for all Unmapped Streets (including Record Streets) to be the same color and line thickness, and to differentiate them with dot/dash styles. The legend item for Unmapped Streets could be a line that's half dashed / half dotted. And the legend item for Record Streets could be just one of those two. 

I'd love to get @kchanba's take on the cartography here.

**Comment by hannahkates** [comment]
Deployed to production
